import type { Plant } from "./types";

/**
 * Hardcoded plants dataset for the POC.
 *
 * Periods reflect typical French temperate climate (zone 8a-8b).
 * Companion associations are based on classical companion planting
 * (compagnonnage végétal) in organic / permaculture gardening.
 *
 * All companion relationships are bilateral: if A lists B, then B lists A.
 */
export const PLANTS: Plant[] = [
    {
        id: "tomate",
        name: "Tomate",
        icon: "noto:tomato",
        category: "legume-fruit",
        phases: {
            sowing: { start: 3, end: 4 },
            planting: { start: 5, end: 5 },
            flowering: { start: 6, end: 8 },
            harvest: { start: 7, end: 10 },
        },
        companions: ["basilic", "carotte", "ail", "oignon", "aubergine", "poivron"],
        description: "Reine du potager, gourmande en soleil et en eau.",
        spacePerPlant: 1,
        yieldPerPlant: 2,
    },
    {
        id: "poivron",
        name: "Poivron",
        icon: "noto:bell-pepper",
        category: "legume-fruit",
        phases: {
            sowing: { start: 2, end: 3 },
            planting: { start: 5, end: 5 },
            flowering: { start: 6, end: 7 },
            harvest: { start: 7, end: 10 },
        },
        companions: ["basilic", "tomate", "oignon", "aubergine", "carotte"],
        description: "Solanacée qui demande beaucoup de chaleur.",
        spacePerPlant: 0.5,
        yieldPerPlant: 1,
    },
    {
        id: "courgette",
        name: "Courgette",
        icon: "noto:cucumber",
        category: "legume-fruit",
        phases: {
            sowing: { start: 4, end: 5 },
            planting: { start: 5, end: 5 },
            flowering: { start: 6, end: 8 },
            harvest: { start: 6, end: 10 },
        },
        companions: ["basilic", "mais", "salade"],
        description: "Production abondante, à récolter jeune pour plus de tendreté.",
        spacePerPlant: 1.5,
        yieldPerPlant: 4,
    },
    {
        id: "aubergine",
        name: "Aubergine",
        icon: "noto:eggplant",
        category: "legume-fruit",
        phases: {
            sowing: { start: 2, end: 3 },
            planting: { start: 5, end: 6 },
            flowering: { start: 6, end: 8 },
            harvest: { start: 7, end: 10 },
        },
        companions: ["basilic", "tomate", "poivron"],
        description: "Solanacée frileuse, à installer après les dernières gelées.",
        spacePerPlant: 0.8,
        yieldPerPlant: 1.5,
    },
    {
        id: "salade",
        name: "Salade",
        icon: "noto:leafy-green",
        category: "legume-feuille",
        phases: {
            sowing: { start: 2, end: 9 },
            harvest: { start: 3, end: 11 },
        },
        companions: ["carotte", "ail", "oignon", "fraise", "brocoli", "courgette"],
        description: "Semez en échelonné pour en avoir toute l'année.",
        spacePerPlant: 0.1,
        yieldPerPlant: 0.3,
    },
    {
        id: "brocoli",
        name: "Brocoli",
        icon: "noto:broccoli",
        category: "legume-feuille",
        phases: {
            sowing: { start: 4, end: 7 },
            planting: { start: 6, end: 8 },
            harvest: { start: 8, end: 11 },
        },
        companions: ["salade", "oignon", "ail", "pomme-de-terre"],
        description: "Crucifère riche en vitamines, apprécie les sols frais.",
        spacePerPlant: 0.5,
        yieldPerPlant: 0.8,
    },
    {
        id: "carotte",
        name: "Carotte",
        icon: "noto:carrot",
        category: "legume-racine",
        phases: {
            sowing: { start: 3, end: 7 },
            harvest: { start: 6, end: 11 },
        },
        companions: ["tomate", "salade", "oignon", "ail", "poivron"],
        description: "Préfère un sol meuble et sans cailloux pour de belles racines.",
        spacePerPlant: 0.02,
        yieldPerPlant: 0.1,
    },
    {
        id: "pomme-de-terre",
        name: "Pomme de terre",
        icon: "noto:potato",
        category: "legume-racine",
        phases: {
            planting: { start: 3, end: 4 },
            flowering: { start: 5, end: 6 },
            harvest: { start: 6, end: 9 },
        },
        companions: ["mais", "brocoli"],
        description: "À butter régulièrement pour favoriser la formation des tubercules.",
        spacePerPlant: 0.15,
        yieldPerPlant: 1,
    },
    {
        id: "ail",
        name: "Ail",
        icon: "noto:garlic",
        category: "condiment",
        phases: {
            planting: { start: 10, end: 3 },
            harvest: { start: 6, end: 7 },
        },
        companions: ["tomate", "fraise", "carotte", "salade", "brocoli", "pomme", "poire"],
        description: "Plantation possible en automne (ail d'hiver) ou fin d'hiver.",
        spacePerPlant: 0.02,
        yieldPerPlant: 0.05,
    },
    {
        id: "oignon",
        name: "Oignon",
        icon: "noto:onion",
        category: "condiment",
        phases: {
            sowing: { start: 2, end: 4 },
            planting: { start: 3, end: 4 },
            harvest: { start: 7, end: 9 },
        },
        companions: ["carotte", "tomate", "salade", "fraise", "brocoli", "poivron", "pomme", "poire"],
        description: "Repousse de nombreux ravageurs, à marier avec la carotte.",
        spacePerPlant: 0.04,
        yieldPerPlant: 0.1,
    },
    {
        id: "basilic",
        name: "Basilic",
        icon: "noto:herb",
        category: "aromatique",
        phases: {
            sowing: { start: 4, end: 5 },
            planting: { start: 5, end: 5 },
            harvest: { start: 6, end: 10 },
        },
        companions: ["tomate", "poivron", "aubergine", "courgette"],
        description: "Protège les solanacées des parasites, à pincer pour qu'il se ramifie.",
        spacePerPlant: 0.1,
        yieldPerPlant: 0.2,
    },
    {
        id: "fraise",
        name: "Fraise",
        icon: "noto:strawberry",
        category: "fruit",
        phases: {
            planting: { start: 9, end: 10 },
            flowering: { start: 4, end: 5 },
            harvest: { start: 5, end: 7 },
        },
        companions: ["ail", "oignon", "salade"],
        description: "Plantation à l'automne pour une récolte dès le printemps suivant.",
        spacePerPlant: 0.1,
        yieldPerPlant: 0.3,
    },
    {
        id: "pomme",
        name: "Pomme",
        icon: "noto:red-apple",
        category: "fruit",
        phases: {
            planting: { start: 10, end: 3 },
            flowering: { start: 4, end: 5 },
            harvest: { start: 8, end: 10 },
        },
        companions: ["ail", "oignon"],
        description: "Arbre fruitier à planter en automne ou fin d'hiver.",
        spacePerPlant: 3,
        yieldPerPlant: 15,
    },
    {
        id: "poire",
        name: "Poire",
        icon: "noto:pear",
        category: "fruit",
        phases: {
            planting: { start: 10, end: 3 },
            flowering: { start: 4, end: 5 },
            harvest: { start: 7, end: 10 },
        },
        companions: ["ail", "oignon"],
        description: "Apprécie un emplacement chaud et abrité du vent.",
        spacePerPlant: 3,
        yieldPerPlant: 12,
    },
    {
        id: "mais",
        name: "Maïs",
        icon: "noto:ear-of-corn",
        category: "cereale",
        phases: {
            sowing: { start: 4, end: 6 },
            flowering: { start: 7, end: 8 },
            harvest: { start: 8, end: 10 },
        },
        companions: ["courgette", "pomme-de-terre"],
        description: "Composant classique du trio « trois sœurs » avec courgette et haricot.",
        spacePerPlant: 0.15,
        yieldPerPlant: 0.3,
    },
];
